version: '3.7'

services:
  db:
    image: 'postgres:latest'
    ports:
        - "5342:5342"
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: always

  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HTTP_PORT=8080
    links:
      - db

volumes:
  db-data: